### ISSUE TITLE
Yirimirai

### ISSUE THREAD

**Issue by zyckk4** [XYCode-Kerman/XYCode-Kerman#1]
先制定的计划先完成，后制定的计划后完成，是**队列**吧

另，Yirimirai现在是啥情况呀）

**Comment by XYCode-Kerman** [comment]
不是队列（FIFO），是栈（FILO）。你可以去翻一下我近期的提交记录

最近学业忙，在准备中考和几个比赛的参赛作品（ASMRE和ItsWA），等整完了我尽快继续YiriMirai相关项目的开发（预计本月内可以恢复开发）

不过我得先说明，YiriMirai库现在已经弃用了，主要原因是以下几点：

1. YiriMirai库兼容的是mirai-api-http，而不是现在的主流标准OneBot v12。现在鹅场在加强风控，保不齐mirai啥时候用不了了，所以我才决定开启YiriMiraiOneBot项目。
2. YiriMiraiOneBot不依赖于mirai和mirai-api-http，但是因为提供风格类似的API接口，我决定沿用YiriMirai这个名称。如果你还在使用YiriMirai，我建议迁移到YiriMiraiOneBot

YiriMiraiOneBot恢复开发之后，还会同时有一个兼容YiriMiraiOneBot的High Level API框架（主要是感觉YiriMirai的API风格比较偏**底层**，不方便开发大型项目。我的GeneralQBOT就是因为这个原因废止的），如果感兴趣可以支持一下
